name: 🐞 Bug Report
description: Report a bug or malfunction in Task Force Canada (TFC)
title: "[BUG] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Task Force Canada – Bug Report
        Please provide accurate and complete information.
        Incomplete reports may be closed or returned for clarification.

  - type: dropdown
    id: category
    attributes:
      label: Affected Category
      description: What type of asset is affected?
      options:
        - Armoured Vehicle
        - Aircraft (Rotary)
        - Aircraft (Fixed Wing)
        - Weapon / Weapon System
        - Sensor / Electronics
        - Gear / Uniform
        - Script / Framework
        - Other
    validations:
      required: true

  - type: input
    id: asset
    attributes:
      label: Asset Name
      description: Exact in-game asset or classname if known
      placeholder: "LAV 6.0 IFV / CH-146 Griffon / AGM-114R"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact on gameplay or stability
      options:
        - Critical – Crash / Game breaking
        - Major – Severely impacts use
        - Moderate – Usable with issues
        - Minor – Cosmetic / visual
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this occur?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Unable to reproduce
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe what is happening
      placeholder: "Describe the issue in detail"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the issue
      placeholder: |
        1. Spawn asset
        2. Enter driver seat
        3. Activate system
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should happen instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TFC Mod Version
      description: Version number or Workshop update date
      placeholder: "v1.5.0 / Updated 2026-01-10"
    validations:
      required: true

  - type: textarea
    id: rpt
    attributes:
      label: RPT / Logs
      description: Paste relevant RPT output or attach files
      render: shell

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I am using the latest TFC mod version
          required: true
        - label: I have checked for duplicate issues
          required: true
