name: 🐞 Bug Report
description: Report a bug or malfunction in Task Force Canada (TFC)
title: "[BUG] "
labels:
  - bug
  - needs-triage

body:
  - type: markdown
    attributes:
      value: |
        ## Task Force Canada — Bug Report
        Please provide accurate and complete information.
        Incomplete reports may be returned for clarification.

  - type: dropdown
    id: affected_category
    attributes:
      label: Affected Category
      description: What type of asset is affected?
      options:
        - Armoured Vehicle
        - Aircraft (Rotary)
        - Aircraft (Fixed Wing)
        - Weapon / Weapon System
        - Sensor / Electronics
        - Gear / Uniform
        - Script / Framework
        - Other
    validations:
      required: true

  - type: dropdown
    id: mod_pack
    attributes:
      label: TFC Mod Pack
      description: Which TFC mod is affected?
      options:
        - TFC_CORE
        - TFC_RCN
        - TFC_CA
        - TFC_RCAF
        - TFC_SF
        - ACE_Compat_TFC_CORE
        - ACE_Compat_TFC_RCN
        - ACE_Compat_TFC_CA
        - ACE_Compat_TFC_RCAF
        - ACE_Compat_TFC_SF
        - Unknown / Not sure
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: Version of the selected mod pack (example: 0.9.9.6)
      placeholder: 'Example: 0.9.9.6'
    validations:
      required: true

  - type: input
    id: asset_name
    attributes:
      label: Asset Name
      description: Exact in-game asset name or classname if known
      placeholder: "Example: LAV 6.0 IFV / tfc_lav6 / CH-146 Griffon / AGM-114R"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact on gameplay or stability
      options:
        - Critical — Crash / Game breaking
        - Major — Severely impacts use
        - Moderate — Usable with issues
        - Minor — Cosmetic / Visual
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this occur?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Unable to reproduce
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Clearly describe what is happening
      placeholder: "Describe the issue in detail…"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps so we can reproduce the issue
      value: |
        1. Spawn asset
        2. Enter driver seat
        3. Activate system
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behaviour
      description: What should happen instead?
      placeholder: "Expected result…"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Helpful details (fill what you can)
      value: |
        - Game: Arma 3 (version/build):
        - Singleplayer or Multiplayer:
        - Server host (Dedicated / Local / Hosted):
        - Mods loaded (besides TFC):
        - ACE enabled? (Yes/No):
        - Repro on vanilla mission? (Yes/No):
    validations:
      required: false

  - type: textarea
    id: rpt_logs
    attributes:
      label: RPT / Logs
      description: Paste relevant RPT output or attach files (screenshots/video also welcome)
      placeholder: "Paste logs here or attach files…"
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I am using the latest version of the selected mod pack
          required: true
        - label: I have checked for duplicate issues
          required: true
